### ISSUE TITLE
perguntar ao profe se  um user precisa de estar registado para fazer download de um arquivo

### ISSUE THREAD

**Issue by SilviaTimoteo** [SilviaTimoteo/ES-Project#13]

**Comment by GAC27** [comment]
download archive nao faz nada
mas user tem de estar activo no gitbob

**Comment by ruims** [comment]
aqui entao é basicamente verificar se esta registado na guarda mas nao ha açao. certo?

@SilviaTimoteo 
@GAC27

**Comment by GAC27** [comment]
sim
